ri_name: Facenet
gpu_mem: 0.585
model_det: C:/Users/Loren/anaconda3/envs/pyppbox/Lib/site-packages/pyppbox/data/modules/facenet/models/det
model_file: C:/Users/Loren/anaconda3/envs/pyppbox/Lib/site-packages/pyppbox/data/modules/facenet/models/20180402-114759/20180402-114759.pb
classifier_pkl: C:/Users/Loren/anaconda3/envs/pyppbox/Lib/site-packages/pyppbox/data/modules/facenet/classifier/gta5.pkl
train_data: C:/Users/Loren/anaconda3/envs/pyppbox/Lib/site-packages/pyppbox/data/datasets/GTA_V_DATASET/face_182x182
batch_size: 1000
min_confidence: 0.75
yl_h_calibration: [-125, 75]
yl_w_calibration: [-55, 55]
---
ri_name: Torchreid
classifier_pkl: C:/Users/Loren/pyppbox/examples/classifier/model_reid_made_by_lolo.pkl
train_data: C:/Users/Loren/anaconda3/envs/pyppbox/Lib/site-packages/pyppbox/data/datasets/TEST_GROUP/body_128x256
model_name: osnet_ain_x1_0
model_path: C:/Users/Loren/anaconda3/envs/pyppbox/Lib/site-packages/pyppbox/data/modules/torchreid/models/torchreid/osnet_ain_ms_d_c.pth.tar
min_confidence: 0.65
device: cpu
